// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufMessage.proto

package client;

public final class ProtobufProto {
  private ProtobufProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtobufMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:client.ProtobufMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *记录版本号
     * </pre>
     *
     * <code>required string version = 1 [default = "1.0"];</code>
     */
    boolean hasVersion();
    /**
     * <pre>
     *记录版本号
     * </pre>
     *
     * <code>required string version = 1 [default = "1.0"];</code>
     */
    java.lang.String getVersion();
    /**
     * <pre>
     *记录版本号
     * </pre>
     *
     * <code>required string version = 1 [default = "1.0"];</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     *消息唯一识别码
     * </pre>
     *
     * <code>required string sn = 2;</code>
     */
    boolean hasSn();
    /**
     * <pre>
     *消息唯一识别码
     * </pre>
     *
     * <code>required string sn = 2;</code>
     */
    java.lang.String getSn();
    /**
     * <pre>
     *消息唯一识别码
     * </pre>
     *
     * <code>required string sn = 2;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    /**
     * <pre>
     *请求类型
     * </pre>
     *
     * <code>required .client.ProtobufMessage.Type reqType = 3 [default = STRMSG];</code>
     */
    boolean hasReqType();
    /**
     * <pre>
     *请求类型
     * </pre>
     *
     * <code>required .client.ProtobufMessage.Type reqType = 3 [default = STRMSG];</code>
     */
    client.ProtobufProto.ProtobufMessage.Type getReqType();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>required int64 timeStamp = 4 [default = -1];</code>
     */
    boolean hasTimeStamp();
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>required int64 timeStamp = 4 [default = -1];</code>
     */
    long getTimeStamp();

    /**
     * <pre>
     *请求类型为STRMSG时，body的编码方式
     * </pre>
     *
     * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
     */
    boolean hasContentEncoding();
    /**
     * <pre>
     *请求类型为STRMSG时，body的编码方式
     * </pre>
     *
     * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
     */
    java.lang.String getContentEncoding();
    /**
     * <pre>
     *请求类型为STRMSG时，body的编码方式
     * </pre>
     *
     * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
     */
    com.google.protobuf.ByteString
        getContentEncodingBytes();

    /**
     * <pre>
     *优先级
     * </pre>
     *
     * <code>required .client.ProtobufMessage.Priority priority = 6 [default = NORMAL];</code>
     */
    boolean hasPriority();
    /**
     * <pre>
     *优先级
     * </pre>
     *
     * <code>required .client.ProtobufMessage.Priority priority = 6 [default = NORMAL];</code>
     */
    client.ProtobufProto.ProtobufMessage.Priority getPriority();

    /**
     * <pre>
     *消息角色
     * </pre>
     *
     * <code>required .client.ProtobufMessage.MessageRole messageRole = 7 [default = REQ];</code>
     */
    boolean hasMessageRole();
    /**
     * <pre>
     *消息角色
     * </pre>
     *
     * <code>required .client.ProtobufMessage.MessageRole messageRole = 7 [default = REQ];</code>
     */
    client.ProtobufProto.ProtobufMessage.MessageRole getMessageRole();

    /**
     * <pre>
     *消息业务分类，如：新增病人/切换拍摄模式,为了防止该协议随业务变化，具体的消息业务分类，需要在本地其它文件进行枚举定义。
     * </pre>
     *
     * <code>optional int32 messageType = 8;</code>
     */
    boolean hasMessageType();
    /**
     * <pre>
     *消息业务分类，如：新增病人/切换拍摄模式,为了防止该协议随业务变化，具体的消息业务分类，需要在本地其它文件进行枚举定义。
     * </pre>
     *
     * <code>optional int32 messageType = 8;</code>
     */
    int getMessageType();

    /**
     * <pre>
     *请求参数，如：文件名
     * </pre>
     *
     * <code>optional string param = 9;</code>
     */
    boolean hasParam();
    /**
     * <pre>
     *请求参数，如：文件名
     * </pre>
     *
     * <code>optional string param = 9;</code>
     */
    java.lang.String getParam();
    /**
     * <pre>
     *请求参数，如：文件名
     * </pre>
     *
     * <code>optional string param = 9;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes();

    /**
     * <pre>
     *文件的MD5
     * </pre>
     *
     * <code>optional string md5 = 10;</code>
     */
    boolean hasMd5();
    /**
     * <pre>
     *文件的MD5
     * </pre>
     *
     * <code>optional string md5 = 10;</code>
     */
    java.lang.String getMd5();
    /**
     * <pre>
     *文件的MD5
     * </pre>
     *
     * <code>optional string md5 = 10;</code>
     */
    com.google.protobuf.ByteString
        getMd5Bytes();

    /**
     * <pre>
     *内容,业务数据（json字符串转换后的byte[]）。如：文件内容
     * </pre>
     *
     * <code>optional bytes body = 11;</code>
     */
    boolean hasBody();
    /**
     * <pre>
     *内容,业务数据（json字符串转换后的byte[]）。如：文件内容
     * </pre>
     *
     * <code>optional bytes body = 11;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code client.ProtobufMessage}
   */
  public  static final class ProtobufMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:client.ProtobufMessage)
      ProtobufMessageOrBuilder {
    // Use ProtobufMessage.newBuilder() to construct.
    private ProtobufMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtobufMessage() {
      version_ = "1.0";
      sn_ = "";
      reqType_ = 2;
      timeStamp_ = -1L;
      contentEncoding_ = "utf-8";
      priority_ = 3;
      messageRole_ = 1;
      messageType_ = 0;
      param_ = "";
      md5_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtobufMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              version_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sn_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              client.ProtobufProto.ProtobufMessage.Type value = client.ProtobufProto.ProtobufMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                reqType_ = rawValue;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timeStamp_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              contentEncoding_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              client.ProtobufProto.ProtobufMessage.Priority value = client.ProtobufProto.ProtobufMessage.Priority.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                priority_ = rawValue;
              }
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              client.ProtobufProto.ProtobufMessage.MessageRole value = client.ProtobufProto.ProtobufMessage.MessageRole.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                messageRole_ = rawValue;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              messageType_ = input.readInt32();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              param_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              md5_ = bs;
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return client.ProtobufProto.internal_static_client_ProtobufMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return client.ProtobufProto.internal_static_client_ProtobufMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              client.ProtobufProto.ProtobufMessage.class, client.ProtobufProto.ProtobufMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code client.ProtobufMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HEARTBEAT = 1;</code>
       */
      HEARTBEAT(1),
      /**
       * <code>STRMSG = 2;</code>
       */
      STRMSG(2),
      /**
       * <code>BIMSG = 3;</code>
       */
      BIMSG(3),
      /**
       * <code>FILE = 4;</code>
       */
      FILE(4),
      ;

      /**
       * <code>HEARTBEAT = 1;</code>
       */
      public static final int HEARTBEAT_VALUE = 1;
      /**
       * <code>STRMSG = 2;</code>
       */
      public static final int STRMSG_VALUE = 2;
      /**
       * <code>BIMSG = 3;</code>
       */
      public static final int BIMSG_VALUE = 3;
      /**
       * <code>FILE = 4;</code>
       */
      public static final int FILE_VALUE = 4;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 1: return HEARTBEAT;
          case 2: return STRMSG;
          case 3: return BIMSG;
          case 4: return FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return client.ProtobufProto.ProtobufMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:client.ProtobufMessage.Type)
    }

    /**
     * Protobuf enum {@code client.ProtobufMessage.Priority}
     */
    public enum Priority
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HIGHTEST = 1;</code>
       */
      HIGHTEST(1),
      /**
       * <code>HIGHT = 2;</code>
       */
      HIGHT(2),
      /**
       * <code>NORMAL = 3;</code>
       */
      NORMAL(3),
      /**
       * <code>LOW = 4;</code>
       */
      LOW(4),
      /**
       * <code>LOWEST = 5;</code>
       */
      LOWEST(5),
      ;

      /**
       * <code>HIGHTEST = 1;</code>
       */
      public static final int HIGHTEST_VALUE = 1;
      /**
       * <code>HIGHT = 2;</code>
       */
      public static final int HIGHT_VALUE = 2;
      /**
       * <code>NORMAL = 3;</code>
       */
      public static final int NORMAL_VALUE = 3;
      /**
       * <code>LOW = 4;</code>
       */
      public static final int LOW_VALUE = 4;
      /**
       * <code>LOWEST = 5;</code>
       */
      public static final int LOWEST_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Priority valueOf(int value) {
        return forNumber(value);
      }

      public static Priority forNumber(int value) {
        switch (value) {
          case 1: return HIGHTEST;
          case 2: return HIGHT;
          case 3: return NORMAL;
          case 4: return LOW;
          case 5: return LOWEST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Priority>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Priority> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Priority>() {
              public Priority findValueByNumber(int number) {
                return Priority.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return client.ProtobufProto.ProtobufMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final Priority[] VALUES = values();

      public static Priority valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Priority(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:client.ProtobufMessage.Priority)
    }

    /**
     * Protobuf enum {@code client.ProtobufMessage.MessageRole}
     */
    public enum MessageRole
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REQ = 1;</code>
       */
      REQ(1),
      /**
       * <code>RESP = 2;</code>
       */
      RESP(2),
      ;

      /**
       * <code>REQ = 1;</code>
       */
      public static final int REQ_VALUE = 1;
      /**
       * <code>RESP = 2;</code>
       */
      public static final int RESP_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageRole valueOf(int value) {
        return forNumber(value);
      }

      public static MessageRole forNumber(int value) {
        switch (value) {
          case 1: return REQ;
          case 2: return RESP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageRole>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageRole> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageRole>() {
              public MessageRole findValueByNumber(int number) {
                return MessageRole.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return client.ProtobufProto.ProtobufMessage.getDescriptor().getEnumTypes().get(2);
      }

      private static final MessageRole[] VALUES = values();

      public static MessageRole valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageRole(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:client.ProtobufMessage.MessageRole)
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object version_;
    /**
     * <pre>
     *记录版本号
     * </pre>
     *
     * <code>required string version = 1 [default = "1.0"];</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *记录版本号
     * </pre>
     *
     * <code>required string version = 1 [default = "1.0"];</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *记录版本号
     * </pre>
     *
     * <code>required string version = 1 [default = "1.0"];</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SN_FIELD_NUMBER = 2;
    private volatile java.lang.Object sn_;
    /**
     * <pre>
     *消息唯一识别码
     * </pre>
     *
     * <code>required string sn = 2;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *消息唯一识别码
     * </pre>
     *
     * <code>required string sn = 2;</code>
     */
    public java.lang.String getSn() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sn_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息唯一识别码
     * </pre>
     *
     * <code>required string sn = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQTYPE_FIELD_NUMBER = 3;
    private int reqType_;
    /**
     * <pre>
     *请求类型
     * </pre>
     *
     * <code>required .client.ProtobufMessage.Type reqType = 3 [default = STRMSG];</code>
     */
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *请求类型
     * </pre>
     *
     * <code>required .client.ProtobufMessage.Type reqType = 3 [default = STRMSG];</code>
     */
    public client.ProtobufProto.ProtobufMessage.Type getReqType() {
      client.ProtobufProto.ProtobufMessage.Type result = client.ProtobufProto.ProtobufMessage.Type.valueOf(reqType_);
      return result == null ? client.ProtobufProto.ProtobufMessage.Type.STRMSG : result;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timeStamp_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>required int64 timeStamp = 4 [default = -1];</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>required int64 timeStamp = 4 [default = -1];</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int CONTENTENCODING_FIELD_NUMBER = 5;
    private volatile java.lang.Object contentEncoding_;
    /**
     * <pre>
     *请求类型为STRMSG时，body的编码方式
     * </pre>
     *
     * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
     */
    public boolean hasContentEncoding() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *请求类型为STRMSG时，body的编码方式
     * </pre>
     *
     * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
     */
    public java.lang.String getContentEncoding() {
      java.lang.Object ref = contentEncoding_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contentEncoding_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *请求类型为STRMSG时，body的编码方式
     * </pre>
     *
     * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
     */
    public com.google.protobuf.ByteString
        getContentEncodingBytes() {
      java.lang.Object ref = contentEncoding_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentEncoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIORITY_FIELD_NUMBER = 6;
    private int priority_;
    /**
     * <pre>
     *优先级
     * </pre>
     *
     * <code>required .client.ProtobufMessage.Priority priority = 6 [default = NORMAL];</code>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *优先级
     * </pre>
     *
     * <code>required .client.ProtobufMessage.Priority priority = 6 [default = NORMAL];</code>
     */
    public client.ProtobufProto.ProtobufMessage.Priority getPriority() {
      client.ProtobufProto.ProtobufMessage.Priority result = client.ProtobufProto.ProtobufMessage.Priority.valueOf(priority_);
      return result == null ? client.ProtobufProto.ProtobufMessage.Priority.NORMAL : result;
    }

    public static final int MESSAGEROLE_FIELD_NUMBER = 7;
    private int messageRole_;
    /**
     * <pre>
     *消息角色
     * </pre>
     *
     * <code>required .client.ProtobufMessage.MessageRole messageRole = 7 [default = REQ];</code>
     */
    public boolean hasMessageRole() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     *消息角色
     * </pre>
     *
     * <code>required .client.ProtobufMessage.MessageRole messageRole = 7 [default = REQ];</code>
     */
    public client.ProtobufProto.ProtobufMessage.MessageRole getMessageRole() {
      client.ProtobufProto.ProtobufMessage.MessageRole result = client.ProtobufProto.ProtobufMessage.MessageRole.valueOf(messageRole_);
      return result == null ? client.ProtobufProto.ProtobufMessage.MessageRole.REQ : result;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 8;
    private int messageType_;
    /**
     * <pre>
     *消息业务分类，如：新增病人/切换拍摄模式,为了防止该协议随业务变化，具体的消息业务分类，需要在本地其它文件进行枚举定义。
     * </pre>
     *
     * <code>optional int32 messageType = 8;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     *消息业务分类，如：新增病人/切换拍摄模式,为了防止该协议随业务变化，具体的消息业务分类，需要在本地其它文件进行枚举定义。
     * </pre>
     *
     * <code>optional int32 messageType = 8;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    public static final int PARAM_FIELD_NUMBER = 9;
    private volatile java.lang.Object param_;
    /**
     * <pre>
     *请求参数，如：文件名
     * </pre>
     *
     * <code>optional string param = 9;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     *请求参数，如：文件名
     * </pre>
     *
     * <code>optional string param = 9;</code>
     */
    public java.lang.String getParam() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *请求参数，如：文件名
     * </pre>
     *
     * <code>optional string param = 9;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MD5_FIELD_NUMBER = 10;
    private volatile java.lang.Object md5_;
    /**
     * <pre>
     *文件的MD5
     * </pre>
     *
     * <code>optional string md5 = 10;</code>
     */
    public boolean hasMd5() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     *文件的MD5
     * </pre>
     *
     * <code>optional string md5 = 10;</code>
     */
    public java.lang.String getMd5() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          md5_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *文件的MD5
     * </pre>
     *
     * <code>optional string md5 = 10;</code>
     */
    public com.google.protobuf.ByteString
        getMd5Bytes() {
      java.lang.Object ref = md5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        md5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     *内容,业务数据（json字符串转换后的byte[]）。如：文件内容
     * </pre>
     *
     * <code>optional bytes body = 11;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <pre>
     *内容,业务数据（json字符串转换后的byte[]）。如：文件内容
     * </pre>
     *
     * <code>optional bytes body = 11;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentEncoding()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageRole()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sn_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, reqType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, timeStamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, contentEncoding_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, priority_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, messageRole_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, messageType_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, param_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, md5_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sn_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, reqType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timeStamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, contentEncoding_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, priority_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, messageRole_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, messageType_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, param_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, md5_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof client.ProtobufProto.ProtobufMessage)) {
        return super.equals(obj);
      }
      client.ProtobufProto.ProtobufMessage other = (client.ProtobufProto.ProtobufMessage) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && getVersion()
            .equals(other.getVersion());
      }
      result = result && (hasSn() == other.hasSn());
      if (hasSn()) {
        result = result && getSn()
            .equals(other.getSn());
      }
      result = result && (hasReqType() == other.hasReqType());
      if (hasReqType()) {
        result = result && reqType_ == other.reqType_;
      }
      result = result && (hasTimeStamp() == other.hasTimeStamp());
      if (hasTimeStamp()) {
        result = result && (getTimeStamp()
            == other.getTimeStamp());
      }
      result = result && (hasContentEncoding() == other.hasContentEncoding());
      if (hasContentEncoding()) {
        result = result && getContentEncoding()
            .equals(other.getContentEncoding());
      }
      result = result && (hasPriority() == other.hasPriority());
      if (hasPriority()) {
        result = result && priority_ == other.priority_;
      }
      result = result && (hasMessageRole() == other.hasMessageRole());
      if (hasMessageRole()) {
        result = result && messageRole_ == other.messageRole_;
      }
      result = result && (hasMessageType() == other.hasMessageType());
      if (hasMessageType()) {
        result = result && (getMessageType()
            == other.getMessageType());
      }
      result = result && (hasParam() == other.hasParam());
      if (hasParam()) {
        result = result && getParam()
            .equals(other.getParam());
      }
      result = result && (hasMd5() == other.hasMd5());
      if (hasMd5()) {
        result = result && getMd5()
            .equals(other.getMd5());
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
      }
      if (hasSn()) {
        hash = (37 * hash) + SN_FIELD_NUMBER;
        hash = (53 * hash) + getSn().hashCode();
      }
      if (hasReqType()) {
        hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
        hash = (53 * hash) + reqType_;
      }
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStamp());
      }
      if (hasContentEncoding()) {
        hash = (37 * hash) + CONTENTENCODING_FIELD_NUMBER;
        hash = (53 * hash) + getContentEncoding().hashCode();
      }
      if (hasPriority()) {
        hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + priority_;
      }
      if (hasMessageRole()) {
        hash = (37 * hash) + MESSAGEROLE_FIELD_NUMBER;
        hash = (53 * hash) + messageRole_;
      }
      if (hasMessageType()) {
        hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageType();
      }
      if (hasParam()) {
        hash = (37 * hash) + PARAM_FIELD_NUMBER;
        hash = (53 * hash) + getParam().hashCode();
      }
      if (hasMd5()) {
        hash = (37 * hash) + MD5_FIELD_NUMBER;
        hash = (53 * hash) + getMd5().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static client.ProtobufProto.ProtobufMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static client.ProtobufProto.ProtobufMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static client.ProtobufProto.ProtobufMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static client.ProtobufProto.ProtobufMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static client.ProtobufProto.ProtobufMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static client.ProtobufProto.ProtobufMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static client.ProtobufProto.ProtobufMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static client.ProtobufProto.ProtobufMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static client.ProtobufProto.ProtobufMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static client.ProtobufProto.ProtobufMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(client.ProtobufProto.ProtobufMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code client.ProtobufMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:client.ProtobufMessage)
        client.ProtobufProto.ProtobufMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return client.ProtobufProto.internal_static_client_ProtobufMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return client.ProtobufProto.internal_static_client_ProtobufMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                client.ProtobufProto.ProtobufMessage.class, client.ProtobufProto.ProtobufMessage.Builder.class);
      }

      // Construct using client.ProtobufProto.ProtobufMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = "1.0";
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        reqType_ = 2;
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStamp_ = -1L;
        bitField0_ = (bitField0_ & ~0x00000008);
        contentEncoding_ = "utf-8";
        bitField0_ = (bitField0_ & ~0x00000010);
        priority_ = 3;
        bitField0_ = (bitField0_ & ~0x00000020);
        messageRole_ = 1;
        bitField0_ = (bitField0_ & ~0x00000040);
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        param_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        md5_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return client.ProtobufProto.internal_static_client_ProtobufMessage_descriptor;
      }

      public client.ProtobufProto.ProtobufMessage getDefaultInstanceForType() {
        return client.ProtobufProto.ProtobufMessage.getDefaultInstance();
      }

      public client.ProtobufProto.ProtobufMessage build() {
        client.ProtobufProto.ProtobufMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public client.ProtobufProto.ProtobufMessage buildPartial() {
        client.ProtobufProto.ProtobufMessage result = new client.ProtobufProto.ProtobufMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.contentEncoding_ = contentEncoding_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.messageRole_ = messageRole_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.param_ = param_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.md5_ = md5_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof client.ProtobufProto.ProtobufMessage) {
          return mergeFrom((client.ProtobufProto.ProtobufMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(client.ProtobufProto.ProtobufMessage other) {
        if (other == client.ProtobufProto.ProtobufMessage.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          bitField0_ |= 0x00000001;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasSn()) {
          bitField0_ |= 0x00000002;
          sn_ = other.sn_;
          onChanged();
        }
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasContentEncoding()) {
          bitField0_ |= 0x00000010;
          contentEncoding_ = other.contentEncoding_;
          onChanged();
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasMessageRole()) {
          setMessageRole(other.getMessageRole());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasParam()) {
          bitField0_ |= 0x00000100;
          param_ = other.param_;
          onChanged();
        }
        if (other.hasMd5()) {
          bitField0_ |= 0x00000200;
          md5_ = other.md5_;
          onChanged();
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasSn()) {
          return false;
        }
        if (!hasReqType()) {
          return false;
        }
        if (!hasTimeStamp()) {
          return false;
        }
        if (!hasContentEncoding()) {
          return false;
        }
        if (!hasPriority()) {
          return false;
        }
        if (!hasMessageRole()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        client.ProtobufProto.ProtobufMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (client.ProtobufProto.ProtobufMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object version_ = "1.0";
      /**
       * <pre>
       *记录版本号
       * </pre>
       *
       * <code>required string version = 1 [default = "1.0"];</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *记录版本号
       * </pre>
       *
       * <code>required string version = 1 [default = "1.0"];</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *记录版本号
       * </pre>
       *
       * <code>required string version = 1 [default = "1.0"];</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *记录版本号
       * </pre>
       *
       * <code>required string version = 1 [default = "1.0"];</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *记录版本号
       * </pre>
       *
       * <code>required string version = 1 [default = "1.0"];</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *记录版本号
       * </pre>
       *
       * <code>required string version = 1 [default = "1.0"];</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sn_ = "";
      /**
       * <pre>
       *消息唯一识别码
       * </pre>
       *
       * <code>required string sn = 2;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *消息唯一识别码
       * </pre>
       *
       * <code>required string sn = 2;</code>
       */
      public java.lang.String getSn() {
        java.lang.Object ref = sn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sn_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息唯一识别码
       * </pre>
       *
       * <code>required string sn = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        java.lang.Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息唯一识别码
       * </pre>
       *
       * <code>required string sn = 2;</code>
       */
      public Builder setSn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一识别码
       * </pre>
       *
       * <code>required string sn = 2;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sn_ = getDefaultInstance().getSn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息唯一识别码
       * </pre>
       *
       * <code>required string sn = 2;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sn_ = value;
        onChanged();
        return this;
      }

      private int reqType_ = 2;
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>required .client.ProtobufMessage.Type reqType = 3 [default = STRMSG];</code>
       */
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>required .client.ProtobufMessage.Type reqType = 3 [default = STRMSG];</code>
       */
      public client.ProtobufProto.ProtobufMessage.Type getReqType() {
        client.ProtobufProto.ProtobufMessage.Type result = client.ProtobufProto.ProtobufMessage.Type.valueOf(reqType_);
        return result == null ? client.ProtobufProto.ProtobufMessage.Type.STRMSG : result;
      }
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>required .client.ProtobufMessage.Type reqType = 3 [default = STRMSG];</code>
       */
      public Builder setReqType(client.ProtobufProto.ProtobufMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        reqType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>required .client.ProtobufMessage.Type reqType = 3 [default = STRMSG];</code>
       */
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqType_ = 2;
        onChanged();
        return this;
      }

      private long timeStamp_ = -1L;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>required int64 timeStamp = 4 [default = -1];</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>required int64 timeStamp = 4 [default = -1];</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>required int64 timeStamp = 4 [default = -1];</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00000008;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>required int64 timeStamp = 4 [default = -1];</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timeStamp_ = -1L;
        onChanged();
        return this;
      }

      private java.lang.Object contentEncoding_ = "utf-8";
      /**
       * <pre>
       *请求类型为STRMSG时，body的编码方式
       * </pre>
       *
       * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
       */
      public boolean hasContentEncoding() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *请求类型为STRMSG时，body的编码方式
       * </pre>
       *
       * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
       */
      public java.lang.String getContentEncoding() {
        java.lang.Object ref = contentEncoding_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contentEncoding_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求类型为STRMSG时，body的编码方式
       * </pre>
       *
       * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
       */
      public com.google.protobuf.ByteString
          getContentEncodingBytes() {
        java.lang.Object ref = contentEncoding_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentEncoding_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求类型为STRMSG时，body的编码方式
       * </pre>
       *
       * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
       */
      public Builder setContentEncoding(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        contentEncoding_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求类型为STRMSG时，body的编码方式
       * </pre>
       *
       * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
       */
      public Builder clearContentEncoding() {
        bitField0_ = (bitField0_ & ~0x00000010);
        contentEncoding_ = getDefaultInstance().getContentEncoding();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求类型为STRMSG时，body的编码方式
       * </pre>
       *
       * <code>required string contentEncoding = 5 [default = "utf-8"];</code>
       */
      public Builder setContentEncodingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        contentEncoding_ = value;
        onChanged();
        return this;
      }

      private int priority_ = 3;
      /**
       * <pre>
       *优先级
       * </pre>
       *
       * <code>required .client.ProtobufMessage.Priority priority = 6 [default = NORMAL];</code>
       */
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *优先级
       * </pre>
       *
       * <code>required .client.ProtobufMessage.Priority priority = 6 [default = NORMAL];</code>
       */
      public client.ProtobufProto.ProtobufMessage.Priority getPriority() {
        client.ProtobufProto.ProtobufMessage.Priority result = client.ProtobufProto.ProtobufMessage.Priority.valueOf(priority_);
        return result == null ? client.ProtobufProto.ProtobufMessage.Priority.NORMAL : result;
      }
      /**
       * <pre>
       *优先级
       * </pre>
       *
       * <code>required .client.ProtobufMessage.Priority priority = 6 [default = NORMAL];</code>
       */
      public Builder setPriority(client.ProtobufProto.ProtobufMessage.Priority value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        priority_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *优先级
       * </pre>
       *
       * <code>required .client.ProtobufMessage.Priority priority = 6 [default = NORMAL];</code>
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000020);
        priority_ = 3;
        onChanged();
        return this;
      }

      private int messageRole_ = 1;
      /**
       * <pre>
       *消息角色
       * </pre>
       *
       * <code>required .client.ProtobufMessage.MessageRole messageRole = 7 [default = REQ];</code>
       */
      public boolean hasMessageRole() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       *消息角色
       * </pre>
       *
       * <code>required .client.ProtobufMessage.MessageRole messageRole = 7 [default = REQ];</code>
       */
      public client.ProtobufProto.ProtobufMessage.MessageRole getMessageRole() {
        client.ProtobufProto.ProtobufMessage.MessageRole result = client.ProtobufProto.ProtobufMessage.MessageRole.valueOf(messageRole_);
        return result == null ? client.ProtobufProto.ProtobufMessage.MessageRole.REQ : result;
      }
      /**
       * <pre>
       *消息角色
       * </pre>
       *
       * <code>required .client.ProtobufMessage.MessageRole messageRole = 7 [default = REQ];</code>
       */
      public Builder setMessageRole(client.ProtobufProto.ProtobufMessage.MessageRole value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        messageRole_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息角色
       * </pre>
       *
       * <code>required .client.ProtobufMessage.MessageRole messageRole = 7 [default = REQ];</code>
       */
      public Builder clearMessageRole() {
        bitField0_ = (bitField0_ & ~0x00000040);
        messageRole_ = 1;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       *消息业务分类，如：新增病人/切换拍摄模式,为了防止该协议随业务变化，具体的消息业务分类，需要在本地其它文件进行枚举定义。
       * </pre>
       *
       * <code>optional int32 messageType = 8;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       *消息业务分类，如：新增病人/切换拍摄模式,为了防止该协议随业务变化，具体的消息业务分类，需要在本地其它文件进行枚举定义。
       * </pre>
       *
       * <code>optional int32 messageType = 8;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       *消息业务分类，如：新增病人/切换拍摄模式,为了防止该协议随业务变化，具体的消息业务分类，需要在本地其它文件进行枚举定义。
       * </pre>
       *
       * <code>optional int32 messageType = 8;</code>
       */
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000080;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息业务分类，如：新增病人/切换拍摄模式,为了防止该协议随业务变化，具体的消息业务分类，需要在本地其它文件进行枚举定义。
       * </pre>
       *
       * <code>optional int32 messageType = 8;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object param_ = "";
      /**
       * <pre>
       *请求参数，如：文件名
       * </pre>
       *
       * <code>optional string param = 9;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       *请求参数，如：文件名
       * </pre>
       *
       * <code>optional string param = 9;</code>
       */
      public java.lang.String getParam() {
        java.lang.Object ref = param_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            param_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求参数，如：文件名
       * </pre>
       *
       * <code>optional string param = 9;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        java.lang.Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求参数，如：文件名
       * </pre>
       *
       * <code>optional string param = 9;</code>
       */
      public Builder setParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求参数，如：文件名
       * </pre>
       *
       * <code>optional string param = 9;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000100);
        param_ = getDefaultInstance().getParam();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求参数，如：文件名
       * </pre>
       *
       * <code>optional string param = 9;</code>
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        param_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object md5_ = "";
      /**
       * <pre>
       *文件的MD5
       * </pre>
       *
       * <code>optional string md5 = 10;</code>
       */
      public boolean hasMd5() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       *文件的MD5
       * </pre>
       *
       * <code>optional string md5 = 10;</code>
       */
      public java.lang.String getMd5() {
        java.lang.Object ref = md5_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            md5_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *文件的MD5
       * </pre>
       *
       * <code>optional string md5 = 10;</code>
       */
      public com.google.protobuf.ByteString
          getMd5Bytes() {
        java.lang.Object ref = md5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          md5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *文件的MD5
       * </pre>
       *
       * <code>optional string md5 = 10;</code>
       */
      public Builder setMd5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        md5_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *文件的MD5
       * </pre>
       *
       * <code>optional string md5 = 10;</code>
       */
      public Builder clearMd5() {
        bitField0_ = (bitField0_ & ~0x00000200);
        md5_ = getDefaultInstance().getMd5();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *文件的MD5
       * </pre>
       *
       * <code>optional string md5 = 10;</code>
       */
      public Builder setMd5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        md5_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *内容,业务数据（json字符串转换后的byte[]）。如：文件内容
       * </pre>
       *
       * <code>optional bytes body = 11;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <pre>
       *内容,业务数据（json字符串转换后的byte[]）。如：文件内容
       * </pre>
       *
       * <code>optional bytes body = 11;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       *内容,业务数据（json字符串转换后的byte[]）。如：文件内容
       * </pre>
       *
       * <code>optional bytes body = 11;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容,业务数据（json字符串转换后的byte[]）。如：文件内容
       * </pre>
       *
       * <code>optional bytes body = 11;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000400);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:client.ProtobufMessage)
    }

    // @@protoc_insertion_point(class_scope:client.ProtobufMessage)
    private static final client.ProtobufProto.ProtobufMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new client.ProtobufProto.ProtobufMessage();
    }

    public static client.ProtobufProto.ProtobufMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProtobufMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufMessage>() {
      public ProtobufMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtobufMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtobufMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufMessage> getParserForType() {
      return PARSER;
    }

    public client.ProtobufProto.ProtobufMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_client_ProtobufMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_client_ProtobufMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ProtobufMessage.proto\022\006client\"\373\003\n\017Prot" +
      "obufMessage\022\024\n\007version\030\001 \002(\t:\0031.0\022\n\n\002sn\030" +
      "\002 \002(\t\0225\n\007reqType\030\003 \002(\0162\034.client.Protobuf" +
      "Message.Type:\006STRMSG\022\025\n\ttimeStamp\030\004 \002(\003:" +
      "\002-1\022\036\n\017contentEncoding\030\005 \002(\t:\005utf-8\022:\n\010p" +
      "riority\030\006 \002(\0162 .client.ProtobufMessage.P" +
      "riority:\006NORMAL\022=\n\013messageRole\030\007 \002(\0162#.c" +
      "lient.ProtobufMessage.MessageRole:\003REQ\022\023" +
      "\n\013messageType\030\010 \001(\005\022\r\n\005param\030\t \001(\t\022\013\n\003md" +
      "5\030\n \001(\t\022\014\n\004body\030\013 \001(\014\"6\n\004Type\022\r\n\tHEARTBE",
      "AT\020\001\022\n\n\006STRMSG\020\002\022\t\n\005BIMSG\020\003\022\010\n\004FILE\020\004\"D\n" +
      "\010Priority\022\014\n\010HIGHTEST\020\001\022\t\n\005HIGHT\020\002\022\n\n\006NO" +
      "RMAL\020\003\022\007\n\003LOW\020\004\022\n\n\006LOWEST\020\005\" \n\013MessageRo" +
      "le\022\007\n\003REQ\020\001\022\010\n\004RESP\020\002B\027\n\006clientB\rProtobu" +
      "fProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_client_ProtobufMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_client_ProtobufMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_client_ProtobufMessage_descriptor,
        new java.lang.String[] { "Version", "Sn", "ReqType", "TimeStamp", "ContentEncoding", "Priority", "MessageRole", "MessageType", "Param", "Md5", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
